server:
  servlet:
    context-path: /backend

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${DB_CLOUD_SQL_INSTANCE:linhvu-hello-gcp-360004:asia-east1:gcp-hello-db}


  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
#        generate_statistics: true
#        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 1
